name: Local ollama
version: 1.0.0
schema: v1
models:
  - name: qwen2.5 3B
    provider: anthropic
    model: qwen2.5:3b
    #apiBase: http://localhost:11434
    apiBase: http://localhost:8000/v1
    apiKey: "ollama"
    requestOptions:
      timeout: 300000
      num_ctx: 32768
    capabilities:
      - tool_use
      - image_input
    roles:
      - chat
      - edit
      - apply
